[project]
name = "backend"
version = "0.0.1"
authors = [
  { name="Tristan Solus"},
  { name="Victor Journé"}
]
description = "Backend to serve prepare_data package and launch kubernetes job"
readme = "README.md"
requires-python = ">=3.7"
[tool.pytest.ini_options]
pythonpath = [
  "app"
]
