apiVersion: v1
kind: Secret
metadata:
  name: kubeconfig
type: Opaque
stringData:
  config.yaml: |-
    apiVersion: v1
    clusters:
    - cluster:
        #certificate-authority-data: XXXX
        server: https://10.0.0.130:6443


        insecure-skip-tls-verify: true
      name: cluster.local
    contexts:
    - context:
        cluster: cluster.local
        user: kubernetes-admin
      name: kubernetes-admin@cluster.local
    current-context: kubernetes-admin@cluster.local
    kind: Config
    preferences: {}
    users:
    - name: kubernetes-admin
      user:
        client-certificate-data: XXXX
        client-key-data: XXXXXX